### ISSUE TITLE
How to know which plugin handle has sent slowlink?

### ISSUE THREAD

**Issue by anildigital** [ndarilek/elixir-janus#2]
Hi,

Current plugin implement doesn't send sender details when a slow link event is 
https://github.com/ndarilek/elixir-janus/blob/master/lib/janus/session.ex#L136
See only ```:slowlink, uplink, nacks``` has been notified.. what if receiver wants which peer connection has caused this?

Is there anything that I am missing to use this plugin properly?

**Comment by ndarilek** [comment]
You're right, could've sworn I was sending session/handle PIDs along 
with the event. All events now include either the session or plugin PID. 
Please let me know if that helps.

**Comment by anildigital** [comment]
@ndarilek thanks. It helped.
