### ISSUE TITLE
In poll, very first time, event received when session handles is empty i.e. %{}

### ISSUE THREAD

**Issue by anildigital** [ndarilek/elixir-janus#4]
Hi,

I noticed, when we 

```    
{:ok, session} = Janus.Session.start("http://localhost:8088/janus")
{:ok, handle} = session
    |> Janus.Session.attach_plugin("janus.plugin.videoroom")
```

But for one of the first events that's received, session handles is empty i.e. %{}

```
session comes as %{}
pid as #PID<0.488.0>
data as %{janus: "event", plugindata: %{data: %{description: "myapp", id: 4432795580198982, publishers: [], room: 1234, videoroom: "joined"}, plugin: "janus.plugin.videoroom"}, sender: 3661138351890247, session_id: 2964530471454478, transaction: "59064156"}
```
above comes when you put logging statements at line
https://github.com/ndarilek/elixir-janus/blob/master/lib/janus/session.ex#L128

**Comment by anildigital** [comment]
I expect session data should never be %{} when you attach plugin, but not sure why it is empty very first time. This is causing issues in implementation. Thanks.

Basically above event is lost as it doesn't get caught in plugin case, as related sender is not present in session handles.

**Comment by ndarilek** [comment]
What happens if you delay a few seconds between starting the session and 
adding the plugin?

Maybe there's a race condition where the initial `GET` is still in 
flight and hasn't quite updated the data structure yet.

**Comment by ndarilek** [comment]
I just committed some code that may help with this. I'm refetching the 
session before doing the handle match, as the data may be stale partway 
through the poll. Give that a shot and see if that helps.

**Comment by anildigital** [comment]
This change worked. Thanks.
