### ISSUE TITLE
Event not captured

### ISSUE THREAD

**Issue by anildigital** [ndarilek/elixir-janus#7]
I do following call

```
    Janus.Plugin.message(pid, %{request: "create", description: "Test 123"})
```

I see
```
[debug] POST http://localhost:8088/janus/7709688106744232/5240411241993472 (%{body: %{description: "Test 123", request: "create"}, janus: "message"})
[debug] %{janus: "success", plugindata: %{data: %{room: 4477004120052352, videoroom: "created"}, plugin: "janus.plugin.videoroom"}, sender: 5240411241993472, session_id: 7709688106744232, transaction: "992413567"}
```

But none of above is even captured at this level https://github.com/ndarilek/elixir-janus/blob/master/lib/janus/session.ex#L123

I also see none of ack messages are captured too which can be seen debug statements.
```
[debug] %{janus: "ack", session_id: 7709688106744232, transaction: "333576542"}
```

I am wondering where are all these going? Is it being eaten by any unknown PID?

**Comment by anildigital** [comment]
My bad, I was so used to receiving events from handle_event, could not think about this is synchronous call. Closing this issue.

**Comment by ndarilek** [comment]
Oh, you closed this? Did you figure it out? I was about to start 
debugging, but won't if you have a fix. :)

Thanks.

**Comment by anildigital** [comment]
@ndarilek Above call are synchronous and response doesn't come in callback events. It comes immediately after the HTTP call in HTTP response of same request unlike others. I was able to progress knowing this.
